### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by naomi172839** [jwolle1/jeopardy_clue_dataset#1]
The master zip file does not contain all of the seasons as one .tsv as it seems to suggest.  I have created a new zip with all of the seasons combined into one.  This may save people some time cleaning data in the future and may save you some work!
[all.zip](https://github.com/jwolle1/jeopardy_clue_dataset/files/3465506/all.zip)

**Comment by jwolle1** [comment]
I double-checked and _master_season1-35.tsv_ appears to be correct. Your _all.tsv_ contains 349,676 lines, while _master_season1-35.tsv_ contains 349,641 lines. Yours has 35 more lines.

I checked which lines in your file do not appear in the original. 34 of the 35 are repeats of the header row, i.e.

`round	value	daily_double	category	comments	answer	question	air_date	notes`

And the 35th is an extraneous character in the final line.

If you still believe some clues are missing, please give me an example or two and I'll take a look. Note that your file and _master_season1-35.tsv_ are both 51.0 MB when unzipped.

Thanks for keeping an eye out regardless.

**Comment by naomi172839** [comment]
I am unsure what happened  as it appears to have corrected itself when I unzipped the file again.  Apologies for the unnecessary issue post and thank you for compiling this dataset!

**Comment by jwolle1** [comment]
Okay, great. No problem and thanks again.
