### ISSUE TITLE
Scraper code?

### ISSUE THREAD

**Issue by ryanmcgorman** [jwolle1/jeopardy_clue_dataset#2]
Hi, would it be possible to share the code you used to scrape the info (perhaps in a different repo)? I'm interested in scraping some additional information (clue number, contestant scores, etc.). Thanks in advance.

**Comment by jwolle1** [comment]
Apologies but I'd rather not share that, partially because it would reveal the data source and partially because the code is so poorly written. I know that you know where the data came from—it's not a well kept secret—but I would prefer just to share the dataset and leave it at that.

**Comment by ryanmcgorman** [comment]
All good, yeah I get the hesitation about the data source. And I appreciate the quick reply.

**Comment by ayancey** [comment]
Let's just say said site does not take kindly to scraping.
