### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by NikilXYZ** [jwolle1/jeopardy_clue_dataset#4]
I'm considering using your dataset as an API for a Jeopardy game that I'd like to build. 
There are a couple other APIs that I've found, but they don't seem to be as up to date as yours as far as I can tell.
http://jservice.io/
https://cluebase.readthedocs.io/en/latest/

**Comment by jwolle1** [comment]
Yes, I've been updating the dataset once a year shortly after the season ends. I currently have no plans to stop.

As I said in the README, "please don't use the data to make a public-facing web site, app, or any other product." If you'd like to make a game for your personal use that sounds great.

**Comment by NikilXYZ** [comment]
great! yea for personal use :)
