### ISSUE TITLE
Separate value and daily double bid

### ISSUE THREAD

**Issue by NikilXYZ** [jwolle1/jeopardy_clue_dataset#5]
Looks like j-archive does know the original position on the board. That should actually be the value #. Daily double $ should be a separate field that is blank unless it was a daily double question

**Comment by jwolle1** [comment]
Sorry, I don't know anything about j-archive. You're welcome to fork the repository and add that information.

**Comment by NikilXYZ** [comment]
oh where are you compiling these questions from?
