### ISSUE TITLE
Proposal for score dataset

### ISSUE THREAD

**Issue by ayancey** [jwolle1/jeopardy_clue_dataset#7]
Hi,

I'm building a Jeopardy-related game that uses data from it. I'd like to include a dataset which includes players and their scores at the end of each game. What do you think?

Thanks,
Alex

**Comment by jwolle1** [comment]
Sure, I'm open to that. My first goal is to make the data as approachable as possible for non-tech people, but I think I could add a new folder for things like scoring data.

How about a column for the name of each player (left, middle, right), then columns for each score after the Single, Double, and Final rounds? Like this:

- season
- air_date
- name_left
- name_middle
- name_right
- single_left
- single_middle
- single_right
- double_left
- double_middle
- double_right
- final_left
- final_middle
- final_right

**Comment by jwolle1** [comment]
This has been added. Thanks for the suggestion.
